create table if not exists public.districts (
  id text primary key,
  name text not null,
  population_share numeric not null check (population_share >= 0 and population_share <= 1),
  indicators jsonb not null default '{}'::jsonb,
  base_score numeric not null check (base_score >= 0 and base_score <= 100),
  profile text not null default ''
);

create table if not exists public.measures (
  id text primary key,
  direction text not null,
  name text not null,
  scope text not null check (scope in ('city', 'district')),
  cost numeric not null check (cost >= 0),
  lag_quarters integer not null check (lag_quarters >= 0),
  effects jsonb not null default '{}'::jsonb
);

create table if not exists public.scenarios (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  selections jsonb not null default '[]'::jsonb,
  score numeric check (score >= 0 and score <= 100),
  created_at timestamptz not null default now()
);

create table if not exists public.ai_analyses (
  id bigint generated by default as identity primary key,
  scenario_id uuid not null references public.scenarios(id) on delete cascade,
  summary text not null,
  strengths jsonb not null default '[]'::jsonb,
  risks jsonb not null default '[]'::jsonb,
  tradeoffs jsonb not null default '[]'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  source text not null check (source in ('openai', 'fallback')),
  created_at timestamptz not null default now()
);

alter table public.scenarios enable row level security;

create policy "Users can read their scenarios"
  on public.scenarios for select using (auth.uid() = user_id);
create policy "Users can create their scenarios"
  on public.scenarios for insert with check (auth.uid() = user_id);

alter table public.districts enable row level security;
create policy "Authenticated users can read districts"
  on public.districts for select to authenticated using (true);

alter table public.measures enable row level security;
create policy "Authenticated users can read measures"
  on public.measures for select to authenticated using (true);
